version: "2"
services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: sqlDb
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_ROOT_PASSWORD: pass
        ports: 
            - "3306:3306"
        volumes:
            - ./data:/docker-entrypoint-initdb.d
